In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [4]:
a = np.arange(0, 20, step=1)

In [5]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
a[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
a[0:20:3]

array([ 0,  3,  6,  9, 12, 15, 18])

In [8]:
[x for x in a if x%2==0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
[x for x in a if x%3==0]

[0, 3, 6, 9, 12, 15, 18]