In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,55,60])

chinese_score = np.array([65,90,82,72,66,77])

In [4]:
english_score

array([55, 89, 76, 65, 48, 70])

In [5]:
math_score

array([60, 85, 60, 68, 55, 60])

In [6]:
chinese_score

array([65, 90, 82, 72, 66, 77])

In [7]:
np.greater(english_score,math_score)

array([False,  True,  True, False, False,  True])

In [ ]:
#三位英文比數學高(TRUE)