In [17]:
import numpy as np
#Q1.比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[5 7 4 ... 6 6 5]
  [9 5 9 ... 5 4 0]
  [5 5 5 ... 8 5 1]
  ...
  [6 4 4 ... 3 4 1]
  [1 0 0 ... 1 8 6]
  [9 5 7 ... 9 2 3]]

 [[7 8 5 ... 0 6 8]
  [8 6 7 ... 8 6 7]
  [2 2 6 ... 1 0 1]
  ...
  [6 8 7 ... 7 3 4]
  [5 3 5 ... 6 7 5]
  [8 4 4 ... 8 6 2]]

 [[9 6 2 ... 7 1 0]
  [3 5 7 ... 2 1 3]
  [8 8 2 ... 5 7 1]
  ...
  [0 0 8 ... 2 1 6]
  [5 7 3 ... 3 5 2]
  [9 4 1 ... 5 3 1]]

 ...

 [[5 6 9 ... 2 8 6]
  [2 4 0 ... 1 8 2]
  [9 5 4 ... 4 8 1]
  ...
  [9 5 4 ... 5 9 2]
  [9 8 0 ... 1 0 5]
  [0 4 9 ... 0 4 3]]

 [[6 6 7 ... 7 2 4]
  [8 9 1 ... 7 4 9]
  [7 5 8 ... 8 9 3]
  ...
  [3 6 4 ... 5 8 2]
  [8 5 5 ... 9 7 0]
  [6 1 8 ... 7 3 2]]

 [[7 3 5 ... 4 2 4]
  [0 7 8 ... 7 3 2]
  [3 0 6 ... 3 5 5]
  ...
  [9 9 8 ... 4 5 6]
  [8 6 3 ... 3 6 9]
  [3 0 2 ... 7 5 9]]]


In [18]:
#直接全部+1
%timeit -n 10 a = 2
Z_1 = Z + 1
print(Z[0,0,0])
print(Z_1[0,0,0])

34.3 ns ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
5
6


In [20]:
#flat攤平
%timeit -n 10 a = 2
Z_2 = []
for i in Z.flat:
    Z_2.append(i+1)
Z_2_array = np.array(Z_2, dtype = int).reshape(100,100,100)
print(Z[0,0,0])
print(Z_2_array[0,0,0])

57.1 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
5
6


In [21]:
#nditer
%timeit -n 10 a = 2
Z_3 = []
for i in np.nditer(Z, order = 'C'):
    Z_3.append(i+1)
Z_3_array = np.array(Z_3, dtype = int).reshape(100,100,100)
print(Z[0,0,0])
print(Z_3_array[0,0,0])

45.7 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
5
6


In [22]:
#Q2. 如何從一個陣列中，找出出現頻率最高的數值與位置？
Z = np.random.randint(0,10,50)
print(Z)

[6 8 0 9 3 9 2 8 8 2 6 9 6 6 7 6 0 4 2 6 0 0 6 8 6 1 7 5 4 7 3 3 0 1 9 6 0
 4 4 7 8 4 1 1 5 5 1 4 8 0]


In [23]:
uni,con=np.unique(Z,return_counts=True)
print('頻率最高的數值:',np.max(uni))
print('頻率最高的數值的次數:',con[np.argmax(uni)])
print('頻率最高的數值的位置:',np.where(Z==np.max(uni))[0])
#np.where()[0] 表示行索引，np.where()[1]表示列索引

頻率最高的數值: 9
頻率最高的數值的次數: 4
頻率最高的數值的位置: [ 3  5 11 34]


In [24]:
#Q3.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))

[7, 2, 5, 9, 4, 5]
[7, 2, 5, 9, 4, 5]
[[9, 6, 5, 4], [9, 5, 0, 3], [3, 2, 9, 0]]
[array([9, 6, 5, 4]), array([9, 5, 0, 3]), array([3, 2, 9, 0])]
[[[0, 0], [5, 2], [4, 9]], [[1, 3], [4, 3], [3, 2]]]
[array([[0, 0],
       [5, 2],
       [4, 9]]), array([[1, 3],
       [4, 3],
       [3, 2]])]


In [25]:
tolist_ = lambda arr: list(map(tolist_, arr)) if isinstance(arr, np.ndarray) else arr #isinstance is faster than type()
tolist_(c)

[[[0, 0], [5, 2], [4, 9]], [[1, 3], [4, 3], [3, 2]]]

In [26]:
def tolist_2(arr):
    if (isinstance(arr, np.ndarray)):
        return(list(map(tolist_2, arr)))        
    else:
        return(arr)

tolist_2(c)

[[[0, 0], [5, 2], [4, 9]], [[1, 3], [4, 3], [3, 2]]]