In [1]:
import numpy as np 

In [24]:
a = np.arange(10)

In [3]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(a.sum()) 

45


In [5]:
print(np.sum(a))

45


In [7]:
print(sum(a))

45


In [ ]:
#A1：三者結果相同

In [ ]:
#Q2：請對一個 5x5 的隨機矩陣作正規化的操作

In [8]:
b = np.random.random((5, 5))

In [9]:
print(b)

[[0.34198437 0.29791187 0.47216434 0.05037056 0.1454855 ]
 [0.33583041 0.79236779 0.31456381 0.38946277 0.78373868]
 [0.90677815 0.06286538 0.56909916 0.62909605 0.17956511]
 [0.94080427 0.30645033 0.52235492 0.72144381 0.38283223]
 [0.53580644 0.49326626 0.10623766 0.00172594 0.96747758]]


In [12]:
np.nanmax(b)

0.9674775759537587

In [13]:
np.nanmin(b)

0.0017259364041736225

In [14]:
print(np.sort(b))

[[0.05037056 0.1454855  0.29791187 0.34198437 0.47216434]
 [0.31456381 0.33583041 0.38946277 0.78373868 0.79236779]
 [0.06286538 0.17956511 0.56909916 0.62909605 0.90677815]
 [0.30645033 0.38283223 0.52235492 0.72144381 0.94080427]
 [0.00172594 0.10623766 0.49326626 0.53580644 0.96747758]]


In [ ]:
#Q2：請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1

In [25]:
a[np.searchsorted(a,np.nanmax(a))]=1

In [26]:
format(a)

'[0 1 2 3 4 5 6 7 8 1]'