In [1]:
import numpy as np 

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(a.sum()) 
print(a.sum().dtype) 
print(np.sum(a))
print(np.sum(a).dtype)
print(sum(a))
print(sum(a).dtype)

45
int32
45
int32
45
int32


In [ ]:
#A1：三者結果相同

In [ ]:
#Q2：請對一個 5x5 的隨機矩陣作正規化的操作

In [25]:
b = np.random.random((5, 5))
print(b)
normal_b = (b - b.min()) / (b.max() - b.min())
print('normalize b：',normal_b,sep='\n')

[[0.65421639 0.98998611 0.72917502 0.02414094 0.41496156]
 [0.615534   0.19587061 0.72396498 0.69686583 0.6391555 ]
 [0.14144321 0.74548722 0.7281563  0.89453309 0.76166913]
 [0.16516787 0.64659188 0.20381086 0.35534838 0.27919137]
 [0.22793072 0.62790136 0.22468402 0.90690386 0.5991414 ]]
normalize b：
[[0.65235658 1.         0.72996594 0.         0.40464107]
 [0.61230627 0.17780248 0.72457166 0.69651421 0.6367631 ]
 [0.12145038 0.74685498 0.72891119 0.90117151 0.76360913]
 [0.14601401 0.64446244 0.18602352 0.34291981 0.26406968]
 [0.21099633 0.62511098 0.20763481 0.91397974 0.59533399]]


In [ ]:
#Q3：請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1

In [22]:
c = np.arange(10)
c[np.searchsorted(c,np.nanmax(c))] = -1
format(c)

'[ 0  1  2  3  4  5  6  7  8 -1]'

In [23]:
c1 = np.arange(10)
c1[np.max(c1)] = -1
print(c1)

[ 0  1  2  3  4  5  6  7  8 -1]


In [ ]:
#1.將下列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

In [26]:
array1 = np.array(range(30))
array2 = array1.reshape((5, 6), order="F")
print(array1)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [ ]:
#2.呈上題的 array，找出被 6 除餘 1 的數的索引

In [27]:
array3 = np.where(array2%6==1)
print(array3)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))
